[[library]]
name = "Nala & Exa & RipGrep & Bat & ZSH"
install_script = "sudo apt -y install nala exa ripgrep bat zsh"

[[library]]
name = "Bat Configuration"
install_script = """
mkdir -p ~/.local/bin \
  && ln -s /usr/bin/batcat ~/.local/bin/bat
"""

[[library]]
name = "Set ZSH as default shell"
install_script = """
sudo chsh -s $(which zsh) $USER
"""

[[library]]
name = "Zoxide"
allow_async = true
install_script = """
wget -O- -q --show-progress https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh > zoxide_install.sh \
  && bash zoxide_install.sh \
  && rm -rf zoxide_install.sh
"""

[[library]]
name = "NVM"
group = "NVM Setup"
install_script = """
wget -O- -q --show-progress https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh > nvm_install.sh \
  && XDG_CONFIG_HOME=$HOME PROFILE=/dev/null bash nvm_install.sh \
  && rm -rf nvm_install.sh
"""

[[library]]
name = "Install Node 18"
group = "NVM Setup"
install_script = """
. $HOME/nvm/nvm.sh \
nvm install 18
"""

[[library]]
name = "Oh My Zsh"
install_script = """
rm -rf $HOME/.oh-my-zsh \
  && wget -O- -q --show-progress https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > oh-my-zsh.sh \
  && bash oh-my-zsh.sh --unattended \
  && rm -rf oh-my-zsh.sh
"""

[[library]]
name = "Powerlevel10k"
install_script = """
rm -rf $HOME/.oh-my-zsh/custom/themes/powerlevel10k \
  && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
"""

[[library]]
name = "zsh-autosuggestions"
install_script = """
rm -rf $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions \
  && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
"""

[[library]]
name = "Setup .zshrc"
install_script = """
wget -q --show-progress https://gist.githubusercontent.com/brenoprata10/ce65fcba53eef4c33167a093b6c86259/raw/58dcb2b7895a2e29ff96f21c667aba546ad8fbf3/.zshrc -O .zshrc \
  && mv .zshrc $HOME
"""

[[library]]
name = "Neovim"
group = "Neovim Setup"
install_script = """
wget -q --show-progress https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz \
  && sudo rm -rf /opt/nvim \ 
  && sudo tar -C /opt -xzf nvim-linux64.tar.gz \
  && rm -rf nvim-linux64*
"""

[[library]]
name = "Vim-Plug"
group = "Neovim Setup"
install_script = "curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

[[library]]
name = "PlugInstall"
group = "Neovim Setup"
install_script = "/opt/nvim-linux64/bin/nvim --headless +PlugInstall +qall"

[[library]]
name = "Fira Code"
allow_async = true
install_script = """
mkdir -p ~/.local/share/fonts/ \
  && wget -q --show-progress https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip \ 
  && unzip -qo FiraCode.zip -d FiraCode \
  && sudo mv ./FiraCode/* ~/.local/share/fonts \
  && rm -rf Fira*
"""

[[library]]
name = "Git Config"
allow_async = true
install_script = """
git config --global credential.helper store && export GIT_EDITOR=nvim \
  && git config --global core.editor \"nvim\"
"""

[[library]]
name = "Setup Neovim Config"
allow_async = true
install_script = """
rm -rf $HOME/.config/nvim \ 
  && git clone https://github.com/brenoprata10/nvim.git \
  && mv nvim $HOME/.config
"""
