[[library]]
name = "Nala"
install_script = "sudo apt -y install nala"

[[library]]
name = "Zoxide"
install_script = """
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash \
  && rm -rf install.sh
"""

[[library]]
name = "Exa"
install_script = "sudo nala install -y exa"

[[library]]
name = "Bat"
install_script = """
sudo nala install -y bat \
  && mkdir -p ~/.local/bin \
  && ln -s /usr/bin/batcat ~/.local/bin/bat
"""

[[library]]
name = "RipGrep"
install_script = "sudo nala install -y ripgrep"

[[library]]
name = "ZSH"
install_script = """
sudo nala install -y zsh \
  && sudo chsh -s $(which zsh) $USER
"""

[[library]]
name = "NVM"
install_script = """
wget -qO- --show-progress https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
  && rm -rf install.sh
"""

[[library]]
name = "Oh My Zsh"
install_script = """
rm -rf $HOME/.oh-my-zsh \
  && wget -O- -q --show-progress https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh \
  && rm -rf install.sh
"""

[[library]]
name = "Powerlevel10k"
install_script = """
rm -rf $HOME/.oh-my-zsh/custom/themes/powerlevel10k \
  && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
"""

[[library]]
name = "zsh-autosuggestions"
install_script = """
rm -rf $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions \
  && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
"""

[[library]]
name = "Neovim"
install_script = """
wget -q --show-progress https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz \
  && sudo rm -rf /opt/nvim \ 
  && sudo tar -C /opt -xzf nvim-linux64.tar.gz \
  && rm -rf nvim-linux64*
"""

[[library]]
name = "Vim-Plug"
install_script = "curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

[[library]]
name = "Fira Code"
install_script = """
mkdir -p ~/.local/share/fonts/ \
  && wget -q --show-progress https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip \ 
  && unzip FiraCode.zip -d FiraCode \
  && sudo mv ./FiraCode/* ~/.local/share/fonts \
  && rm -rf Fira*
"""

[[library]]
name = "Git Config"
install_script = """
git config --global credential.helper store && export GIT_EDITOR=nvim \
  && git config --global core.editor \"nvim\"
"""

[[library]]
name = "Setup Neovim Config"
install_script = """
rm -rf $HOME/.config/nvim \ 
  && git clone https://github.com/brenoprata10/nvim.git \
  && mv nvim $HOME/.config
"""

[[library]]
name = "Setup .zshrc"
install_script = """
wget -q --show-progress https://gist.githubusercontent.com/brenoprata10/ce65fcba53eef4c33167a093b6c86259/raw/a49055aef74f998a3e47bdbedc049dd81e3fff29/.zshrc -O .zshrc \
  && mv .zshrc $HOME
"""
